### ISSUE TITLE
Jenkins build failed?

### ISSUE THREAD

**Issue by eacousineau** [ros/class_loader#13]
Looks like the Jenkins build failed: http://jenkins.ros.org/job/devel-groovy-class_loader/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/lastBuild/console

Here's the place where the error occurred (processing triggers):

```
Setting up python-rosinstall (0.6.29-1) ...
Processing triggers for python-support ...
Parsing rosdistro file for groovy
devel script failed. Check out the console output above for details.
Traceback (most recent call last):
  File "/home/rosbuild/hudson/workspace/devel-groovy-class_loader/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/jenkins_scripts/devel", line 30, in <module>
    main()
  File "/home/rosbuild/hudson/workspace/devel-groovy-class_loader/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/jenkins_scripts/devel", line 24, in main
    build_in_workspace=options.build_in_workspace, sudo=options.sudo)
  File "/home/rosbuild/hudson/workspace/devel-groovy-class_loader/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/jenkins_scripts/test_repositories.py", line 59, in test_repositories
    sudo, no_chroot)
  File "/home/rosbuild/hudson/workspace/devel-groovy-class_loader/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/jenkins_scripts/test_repositories.py", line 76, in _test_repositories
    release = get_cached_release(index, ros_distro)
  File "/usr/lib/pymodules/python2.7/rosdistro/__init__.py", line 115, in get_cached_release
    cache = get_release_cache(index, dist_name)
  File "/usr/lib/pymodules/python2.7/rosdistro/__init__.py", line 151, in get_release_cache
    yaml_gz_str = load_url(url)
  File "/usr/lib/pymodules/python2.7/rosdistro/loader.py", line 41, in load_url
    fh = urllib2.urlopen(url, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out
```

Who should this error report go to?

**Comment by eacousineau** [comment]
Looks like a similar thing happened here: http://jenkins.ros.org/job/devel-groovy-class_loader/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/52/console

**Comment by dirk-thomas** [comment]
GitHub does not have a 100% availability. Therefore occasionally accessing data from GitHub will fail / time out.

I just retriggered the job and it passed fine.

**Comment by eacousineau** [comment]
Ah, thanks!
Do you know how long it usually takes for the packages to make into the ros Debian apt repositories?

**Comment by dirk-thomas** [comment]
The Debian package is scheduled to build into the _building_ repo withing an hour after the release (or later when the buildfarm is busy). After no builds are running anymore for a specific architecture (and no big breakage has happened) the Debians are synced to _shadow-fixed_. After that it requires manual syncing to _public_ - that can take from hours to several days. It highly depends when "enough" changes have accumulated, no regressions are there and that people have used the packages from _shadow-fixed_ for some time to catch regressions.

**Comment by eacousineau** [comment]
That makes sense. Thank you for letting me know!
(We were able to resolve an issue with our segfaults by finding the root cause of the warning itself so we're not dependent on this bugfix)
